spring:
  kafka:
    streams:
      application-id: kafka-join-test
bootstrap:
  servers: localhost:9092
input:
  topic-1:
    name: topic-1
  topic-2:
    name: topic-2
output:
  topic:
    name: topic-3


